Repository carnisj/bcdi, pull requests merged in 2023-02, with the labels that each got.

#331 Allow 'frames pattern' to list only the indices of the frames to exclude
  bcdi/examples/S11_config_preprocessing.yml
  bcdi/experiment/beamline_factory.py
  bcdi/experiment/detector.py
  bcdi/experiment/diffractometer.py
  bcdi/experiment/loader.py
  bcdi/experiment/rotation_matrix.py
  bcdi/experiment/setup.py
  bcdi/graph/colormap.py
  bcdi/postprocessing/facet_analysis.py
  bcdi/preprocessing/analysis.py
  bcdi/preprocessing/bcdi_utils.py
  bcdi/utils/format.py
  bcdi/utils/io_helper.py
  bcdi/utils/parameters.py
  bcdi/utils/parser.py
  bcdi/utils/utilities.py
  doc/HISTORY.rst
  doc/modules/postprocessing/index.rst
  doc/modules/preprocessing/index.rst
  doc/modules/utils/index.rst
  scripts/postprocessing/bcdi_angular_profile.py
  scripts/postprocessing/bcdi_line_profile.py
  scripts/preprocessing/bcdi_preprocess.py
  tests/utils/test_format.py
  tests/utils/test_parameters.py
  tests/utils/test_utilities.py
Labels: enhancement, ongoing

#332 Facet
  bcdi/postprocessing/facet_analysis.py
Labels: bug

#333 Clean unit tests
  bcdi/postprocessing/analysis.py
  bcdi/postprocessing/facet_analysis.py
  bcdi/postprocessing/postprocessing_utils.py
  bcdi/utils/image_registration.py
  bcdi/utils/utilities.py
  tests/algorithms/__init__.py
  tests/algorithms/test_algorithms_utils.py
  tests/experiment/test_diffractometer.py
  tests/experiment/test_loader.py
  tests/experiment/test_setup.py
  tests/facet_recognition/__init__.py
  tests/facet_recognition/test_facet_utils.py
  tests/graph/test_linecut.py
  tests/postprocessing/test_analysis.py
  tests/postprocessing/test_facet_analysis.py
  tests/simulation/__init__.py
  tests/simulation/test_simulation_utils.py
  tests/simulation/test_supportMaker.py
  tests/utils/test_format.py
  tests/utils/test_io_helper.py
  tests/utils/test_parameters.py
  tests/xcca/__init__.py
  tests/xcca/test_xcca_utils.py
Labels: refactor
